### ISSUE TITLE
nit: need to run npm install to build the app

### ISSUE THREAD

**Issue by gsabran** [github/CopilotForXcode#11]
After running ```sudo ln -s `which npm` /usr/local/bin```, I think you need to run `npm install` from `Server` to be able to build the app. The later step is not described in the [DEVELOPMENT.md](https://github.com/github/CopilotForXcode/blob/main/DEVELOPMENT.md)

**Versions**
- Copilot for Xcode: latest
- Xcode: 16.0.0
- macOS: 14.6.1
- Node: v16.10.0

**Steps to reproduce**
1. Clone the repo
2. Make sure ```sudo ln -s `which npm` /usr/local/bin``` has been run
3. Build the app

**Screenshots**
<img width="861" alt="Screenshot 2024-10-30 at 9 38 38 AM" src="https://github.com/user-attachments/assets/83cf302f-8b0d-47f1-ae5a-a60a1bfef009">

**Logs**

env: node: No such file or directory
cp: Server/node_modules/@github/copilot-language-server/native/darwin-arm64/copilot-language-server: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by gsabran** [comment]
For me, running `npm install` is what solved the issue. I had also run `sudo ln -s `which node` /usr/local/bin` before to be sure that was not the cause.

**Comment by devm33** [comment]
Yep, `npm install` is run as part of [a custom build script](https://developer.apple.com/documentation/xcode/running-custom-scripts-during-a-build): https://github.com/github/CopilotForXcode/blob/a9ad824d0da3908f06bf90cc3c70b2e0d4c879f1/Copilot%20for%20Xcode.xcodeproj/project.pbxproj#L719

However, the `PATH` Xcode uses for custom build scripts is fairly bare, hence the need to link things to standard locations like `/usr/local/bin`

**Comment by gsabran** [comment]
ACK, then maybe `sudo ln -s `which node` /usr/local/bin` is what I was initially missing.

**Comment by devm33** [comment]
Makes sense I'll update DEVELOPMENT.md to mention that, thanks!
