### ISSUE TITLE
Can not login: Getting Certificate Error with GitHub Copilot for Xcode in Enterprise license

### ISSUE THREAD

**Issue by hoangtuanfithou** [github/CopilotForXcode#18]
**Describe the bug**

I cannot log in with GitHub Copilot for Xcode using my company’s enterprise license. Every time I try to log in, I get this error:

"Language server error: Server error: 1001 Could not log in with device flow on github.com: self-signed certificate in certificate chain nil"

**Versions**
- Copilot for Xcode: 0.27.92
- Xcode: 15.1
- macOS: 14.5

**Steps to reproduce**
1. Login with GitHub Copilot for Xcode
2. Finished on the web with copied code
3. Back to app and Refresh Connection

**Screenshots**
<img width="943" alt="Screenshot 2024-11-02 at 0 03 34 PM" src="https://github.com/user-attachments/assets/58922df0-a485-4b4d-bf01-4a1413146958">

**Logs**
[github-copilot-for-xcode.log](https://github.com/user-attachments/files/17605451/github-copilot-for-xcode.log)

Thank you ⭐️

**Comment by devm33** [comment]
Hi @hoangtuanfithou 👋 thanks for trying out Copilot for Xcode!

Ideally, you can either add your proxy certificate to your system trust store or allow GitHub Copilot domains to bypass TLS inspection. See required domains here: [Configuring your proxy server or firewall for Copilot
](https://docs.github.com/en/copilot/managing-copilot/managing-github-copilot-in-your-organization/configuring-your-proxy-server-or-firewall-for-copilot).

If neither of those are possible you can also disable certificate checking in the extension, though this is not recommended as it is less secure.

![Image](https://github.com/user-attachments/assets/de7c3da0-fd3f-437f-b9e6-01263ea5d13a)

See also [Troubleshooting certificate-related errors](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-network-errors-for-github-copilot#troubleshooting-certificate-related-errors)

Will close this out, but feel free to reopen if you're still seeing issues!
