### ISSUE TITLE
Stuttering / flickering when accepting a suggestion

### ISSUE THREAD

**Issue by fmendez** [github/CopilotForXcode#2]
**Describe the bug**

When accepting a suggestion, the entire file stutters / flickers (see attached video)

**Versions**
- Copilot for Xcode: 0.27.0
- Xcode: Version 16.0 (16A242d)
- macOS: 15.0.1

**Steps to reproduce**

Type anything, then accept the suggestion 

**Screenshots / Video**

https://github.com/user-attachments/assets/faec3484-195f-4fab-a002-e077e80ef0fd

**Comment by fmendez** [comment]
fyi, upgrated both the Mac and XCode the latest version just now and seeing the same bug:

Xcode:  Version 16.1 (16B40)
macOS: 15.1 (24B83)

**Comment by wojciech-kulik** [comment]
It looks like you are using some window manager, have you tried disabling it :)?

**Comment by wojciech-kulik** [comment]
Do you use a window manager? Have you tried disabling it?

**Comment by devm33** [comment]
Hi @fmendez, thanks for trying out Copilot for Xcode and for reporting a detailed issue!

Going by the video that looks like the fallback behavior when the extension is not enabled. Either the Xcode Source Editor Extension permission is not enabled or the extension is disabled.

Check for the `GitHub Copilot` item under Xcode's `Editor' menu:

![Image](https://github.com/user-attachments/assets/fb05a39e-749b-4b7a-a104-ff6fc6ff1682)

If the `GitHub Copilot` menu isn't there then the permission needs to be granted. Go to `System Settings > General > Login Items > Extensions > Xcode Source Editor` and enable `GitHub Copilot`.

If the `GitHub Copilot` menu is there but greyed out, then you just need to restart Xcode.

See more in [TROUBLESHOOTING.md](https://github.com/github/copilot-xcode/blob/main/TROUBLESHOOTING.md)

**Comment by devm33** [comment]
Closing this out, but feel free to reopen if you're still seeing issues!

**Comment by dabing1022** [comment]
Very happy, after opening the expansion, it does not beat anymore!
