### ISSUE TITLE
Per project opt-in/opt-out

### ISSUE THREAD

**Issue by krystianpaszek** [github/CopilotForXcode#27]
It'd be great if this plugin had some kind of blacklist so you could opt-out certain projects from Copilot (for safety reasons). Or a whitelist if you'd like to block all the projects by default and only use Copilot in certain allowed project.

**Comment by devm33** [comment]
Hi @krystianpaszek, this is supported via configuration on github.com. See details in [Excluding content from GitHub Copilot
](https://docs.github.com/en/copilot/managing-copilot/managing-github-copilot-in-your-organization/setting-policies-for-copilot-in-your-organization/excluding-content-from-github-copilot)

Copilot for Xcode is missing from the table there, but it is in fact supported (docs PR in progress 🏃)
