### ISSUE TITLE
Copilot with self-sign certificate

### ISSUE THREAD

**Issue by FlorinDMass** [github/CopilotForXcode#29]
**Describe the bug**
Copilot is not working because our Company uses Self-Sign certificate. I know that a lot of companies uses this kind of self-sign certificate.
There is a way to bypass this ?
I know that in VSCode there is and we are using it.

**Versions**
- Copilot for Xcode: 0.28.0
- Xcode: 16.1
- macOS: 14.7

**Steps to reproduce**
1. Have a self-sign root certificate
2. Setup Copilot for Xcode correctly as described in docs
3. Try to use autocomplete feature in Xcode

**Logs**
```
[2024-11-08T15:36:40.121Z] [info] [GitHubCopilot] [29918] statusNotification: {
  "status" : "Warning",
  "message" : "The pending stream has been canceled (caused by: self-signed certificate in certificate chain)"
}
[2024-11-08T15:36:40.121Z] [info] [GitHubCopilot] [29918] window/logMessage: {
  "type" : 4,
  "message" : "[fetchCompletions] request.response: [https:\/\/proxy.business.githubcopilot.com\/v1\/engines\/copilot-codex\/completions] took 73 ms"
}
[2024-11-08T15:36:40.121Z] [info] [GitHubCopilot] [29918] window/logMessage: {
  "message" : "[fetchCompletions] request.error properties {\n  endpoint: 'completions',\n  engineName: 'copilot-codex',\n  uiKind: 'ghostText',\n  request_option_max_tokens: '500',\n  request_option_temperature: '0.2',\n  request_option_top_p: '1',\n  request_option_n: '2',\n  request_option_stop: '[\"\\\\n\\\\n\\\\n\",\"\\\\n```\"]',\n  request_option_stream: 'true',\n  request_option_extra: '{\"language\":\"swift\",\"next_indent\":12,\"trim_by_indentation\":true,\"prompt_tokens\":252,\"suffix_tokens\":36}',\n  headerRequestId: 'c33ca510-c570-4d17-81a2-169d7b8af358',\n  copilot_build: '1183',\n  copilot_buildType: 'prod',\n  copilot_trackingId: '8e717d2206531147157412f90339a701',\n  organizations_list: '3e81dc023b7309f89b18d41310f2e56c',\n  enterprise_list: '1639',\n  sku: 'copilot_for_business_seat',\n  editor_version: 'Xcode\/16.1',\n  editor_plugin_version: 'copilot-xcode\/0.28.0',\n  client_machineid: 'cba18870a8c08a3d04b9890f9afe37a5b1bbc12ad3abebec55a627b8dfff8d81',\n  client_sessionid: '533f68d2-6d19-4ef7-b050-97e7533367b01731078944485',\n  copilot_version: 'copilot\/1.243.0',\n  runtime_version: 'node\/18.5.0',\n  common_extname: 'copilot-xcode',\n  common_extversion: '0.28.0',\n  common_vscodeversion: 'Xcode\/16.1',\n  fetcher: 'HelixFetcher',\n  proxy_enabled: 'false',\n  proxy_auth: 'false',\n  proxy_kerberos_spn: 'false',\n  reject_unauthorized: 'true',\n  'VSCode.ABExp.Features': 'account-aacf;config.editor.experimental.asyncTokenization;copilotchat.renameSuggestionsDelayBeforeFetch;livesharecontinuousaa;mindaroBinariesVersion;portForwardingServiceEnabled-development;portForwardingServiceEnabled-production;portForwardingServiceEnabled-staging;shouldUseGrpcService',\n  'abexp.assignmentcontext': 'vsliv368:30146709;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;asynctok:30898717;f3je6385:31013174;',\n  unique_id: '84ed023d-fa59-492f-916c-208cdfa192df',\n  message: 'FetchError',\n  code: 'ERR_HTTP2_STREAM_CANCEL',\n  errno: '',\n  type: 'system'\n}",
  "type" : 4
}
```

Thanks,
Florin

**Comment by devm33** [comment]
Hi @FlorinDMass, for VS Code are you disabling strict SSL: `"http.proxyStrictSSL": false`?

The equivalent setting for Copilot for Xcode is under Advanced > Proxy, it should be equivalent to the VS Code setting.

![Image](https://github.com/user-attachments/assets/1437b1d9-c2de-4b79-8b41-158e4f4a2242)

**Comment by FlorinDMass** [comment]
Hi @devm33,
For copilot for VSCode our company told us to add : 
```
"github.copilot.advanced": {
        "debug.useElectronFetcher": true
    },
```
And seems to work.

Yep I disable that under Settings -> Advanced and still not working. My first hunch was that settings has to do with when you use a Proxy to authenticate to, right ?
![Screenshot 2024-11-08 at 17 49 47](https://github.com/user-attachments/assets/b54f8553-61f7-45ef-ae27-4b0ce3d234b0)

Thanks,
Florin

**Comment by devm33** [comment]
Hi @FlorinDMass, glad to hear the electron fetcher is working for you in VS Code 🎉 

> My first hunch was that settings has to do with when you use a Proxy to authenticate to, right ?

It's a little mislabelled `ProxyStrictSSL` applies to all network requests regardless of whether an explicit proxy is in use.

I think I figured out the issue here. If you'd like to test, let me know if this build resolves it for you: https://github.com/github/CopilotForXcode/releases/download/0.28.0/GitHubCopilotForXcode_proxyStrictSSL.dmg

**Comment by FlorinDMass** [comment]
@devm33 Everything working fine now.
I should expect next updates to have this fix ?
Thanks for help.

**Comment by devm33** [comment]
👋 This is now out in the latest [Pre-release 0.28.95](https://github.com/github/CopilotForXcode/releases/tag/0.28.95)
