### ISSUE TITLE
Open Chat without any response 

### ISSUE THREAD

**Issue by JackyYangPassion** [github/CopilotForXcode#32]
**Describe the bug**

**Versions**
- Copilot for Xcode: 0.29.0
- Xcode: 15.4
- macOS: 14.5

**Steps to reproduce**
1. open chat 
2. without any response 

**Screenshots**
<img width="435" alt="image" src="https://github.com/user-attachments/assets/1dc90639-af0a-4c20-a29d-1422d2e17d56">

Model test Success
<img width="796" alt="image" src="https://github.com/user-attachments/assets/2d64f3ef-f520-479e-8f6a-b31c6b68c006">

**Logs**
in path can't find Log 
~/Library/Logs/GitHubCopilot/

**Comment by vietstone-ng** [comment]
@JackyYangPassion you're asking about https://github.com/intitni/CopilotForXcode, not this repo, right?

**Comment by JackyYangPassion** [comment]
yes，thanks for your reply
