### ISSUE TITLE
VS code requires restart when paying to renew subscription.

### ISSUE THREAD

**Issue by lmf-git** [github/CopilotForXcode#4]
Could Copilot not detect the renewal rather than having to restart vs code? It also doesn't warn people to restart just keeps directing them to the settings web page

**Comment by devm33** [comment]
Hi @lmf-git, closing this since it doesn't appear to be related to Copilot for Xcode. You likely want to raise on [the community forum](https://github.com/orgs/community/discussions/categories/copilot) or with [support](https://support.github.com/).
